### PR TITLE
Update models

### PR DESCRIPTION
**Pull request by amisevsk**
Move llama2 over to models.yaml and rename some modelkits so that different parameter counts go in different repos

### CODE REVIEW

**Review by bmicklea — APPROVED** [review]

**Review by javisperez — APPROVED** [review]

**Comment by gorkem** [comment]
My only concern with this naming is other tools like huggingface or ollama does not have separete "repos" for different parameter sizes.

**Comment by amisevsk** [comment]
> My only concern with this naming is other tools like huggingface or ollama does not have separete "repos" for different parameter sizes.

 I can undo this change -- @bmicklea what do you think? In my experience I know to not even look at 70B models because they're too big for my machine, but it _is_ what everyone else seems to be doing.

**Comment by bmicklea** [comment]
I'm torn, but I think we stick with the standard for now. At some point we'll want things like collections where we could create a group of small footprint LLMs for example.

**Comment by gorkem** [comment]
@bmicklea sounds like you described a label :)

**Comment by bmicklea** [comment]
Could be a label, yes. I'm thinking more about how it would be presented to the user vs. how it would be implemented.

**Comment by amisevsk** [comment]
For now, I'm leaving things as-is. Net change is adding llama2 to models.yml and sorting the file based on repo to make it a little less unwieldy.

**Pull request merged**
